// Generated by scripts/generate-runtime-config.mjs at build time.
// Values from process.env / Netlify env (and local .env when run locally).
(function(){
  // DashScope API keys are not injected here — combat LLM calls go through generateCombatQuestion (HTTPS Callable).

  // Firebase config must be a JSON string in window.__firebase_config.
  var fbJson = "{\"apiKey\":\"AIzaSyC-8XlMSNVmCKT6ohf7G7dimX_XTxYwOJs\",\"authDomain\":\"mathbattler-724ea.firebaseapp.com\",\"projectId\":\"mathbattler-724ea\",\"storageBucket\":\"mathbattler-724ea.firebasestorage.app\",\"messagingSenderId\":\"444137483234\",\"appId\":\"1:444137483234:web:986426bb2d983808b867bb\",\"measurementId\":\"G-JXVG6F8R0F\"}";
  if (fbJson.trim()) {
    window.__firebase_config = fbJson;
  } else if ("".trim() && "".trim()) {
    window.__firebase_config = JSON.stringify({
      apiKey: "",
      authDomain: "",
      projectId: "",
      storageBucket: "",
      messagingSenderId: "",
      appId: "",
      measurementId: ""
    });
  }
  window.__mathbattler_production_ui__ = false;
})();
